### ISSUE TITLE
Linux bug

### ISSUE THREAD

**Issue by drno88** [EugeneDae/VLC-Scheduler#17]
good day. Firstly, thank you for your work !!! Everything works fine on windows.

There is a problem on Linux - it does not start.
In the last 2 builds, he swears at the same thing
"loop.run_until_complete..."
Here is the error log. Perhaps you have the opportunity to fix this?

Traceback (most recent call last):
  File "src/vlcscheduler.py", line 221, in main
    loop.run_until_complete(main_coro())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "src/vlcscheduler.py", line 141, in main_coro
    primary_playlist.add_source(source)
  File "/home/muzik/VLC-Scheduler-0.3.1/src/playlist.py", line 50, in add_source
    self._sources.append(self.prepare_source(source))
  File "/home/muzik/VLC-Scheduler-0.3.1/src/playlist.py", line 43, in prepare_source
    in utils.parse_time_interval(source['playing_time'])
  File "/home/muzik/VLC-Scheduler-0.3.1/src/utils.py", line 36, in parse_time_interval
    return match[1], match[2]
TypeError: '_sre.SRE_Match' object is not subscriptable

**Comment by drno88** [comment]
all ok
